4 keine sitzungswochen daten
demokratie-live/desktop pull request #22
Opened 2023-01-05 12:56 UTC by appinteractive

Ich kann leider nicht ohne weiteres die nächste Sitzungswoche "erraten" da das `currentConferenceWeek` Query null zurück gibt. Ich Zeige in diesem PR keine KW an sondern nur was ich in `procedures` Query bekomme. Ich extrachiere die KW nicht davon da mir das zu vage ist.

2023-01-10 21:35 UTC, visionmakery commented
@appinteractive geht das jetzt mit @ManAnRucks Update?

2023-01-11 10:41 UTC, appinteractive commented
> @appinteractive geht das jetzt mit @ManAnRuck 's Update?

aktuell klappts ja: https://democracy-app.de/

2023-01-11 11:04 UTC, ManAnRuck commented
Es gab einen Fehler bei der api durch die fehlenden sitzungswochendaten für das Jahr 2023. jetzt sollte die api wieder vernünftige Daten und keinen error mehr ausspielen.

2023-08-19 15:42 UTC, ManAnRuck requested changes
Top Danke!

Hab da mal 2 kleine Kommentare ergänzt 👍

2023-08-19 15:42 UTC, ManAnRuck commented on src/pages/index.tsx
> +      description={`Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen`}
Ich meine nach dem fix des queries können wir das wieder anzeigen, was meinst du dazu?

2023-08-19 15:42 UTC, ManAnRuck commented on src/pages/index.tsx
> +        // description="Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen."
```suggestion
```

2023-08-19 15:42 UTC, ManAnRuck commented on src/pages/index.tsx
> +      description={`Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen`}
zum schnellen testen 🙂
```
curl 'https://internal.api.democracy-app.de/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: https://internal.api.democracy-app.de' --data-binary '{"query":"# Write your query or mutation here\n  query conferenceWeek {\n    currentConferenceWeek {\n      calendarWeek\n      end\n      start\n    }\n  }"}' --compressed
```

2023-08-19 15:42 UTC, ManAnRuck commented on src/pages/index.tsx
> +        // description="Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen."
würd den Kommentar einfach rausnehmen

2023-12-15 20:33 UTC, appinteractive commented on src/pages/index.tsx
> +      description={`Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen`}
@ManAnRuck aktuell gibts einen internal server error

```
{"errors":[{"message":"Cannot read property 'start' of undefined","locations":[{"line":3,"column":5}],"path":["currentConferenceWeek"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null}
```

Darum keine results

2023-12-15 20:56 UTC, appinteractive commented
@ManAnRuck von meiner seite kann das so raus. SIeht gut aus, der Fehler oben scheint sich erledigt zu haben

2023-12-16 11:46 UTC, ManAnRuck commented on src/pages/index.tsx
> +      description={`Vorgänge, die in der kommenden Sitzungswoche zur Abstimmung stehen`}
die sitzungswochendaten haben für das Jahr 2024 gefehlt. hab die jetzt mal eben ergänzt und auf internal deployed. damit sollte der Fehler jetzt für ein Jahr nicht mehr vorkommen ;)

2023-12-16 11:50 UTC, ManAnRuck commented
Dann schalte ich das jetzt live
https://internal.democracy-app.de (hatte übrigens letztens noch ergänzt, dass der Endpunkt auf die internal api via environment variable eingestellt werden kann #33 )

2023-12-16 11:51 UTC, ManAnRuck approved these changes

2023-12-16 11:52 UTC, merged